Feature/integration new endpoints
SciCompMod/ESID-Backend pull request #3
Opened 2023-08-31 09:27 UTC by slymon

2023-09-05 14:58 UTC, lucaspataro requested changes
Inhaltlich kann ich nicht reviewen. Bitte @JonasGilg oder @NXXR auch noch reviewen.

Ich habe beim testen auch noch mehr Fehler gefunden, die scheinbar schon bei letzten PR übersehen worden. Ich halte Sie hier mal fest, ob diese dann in einem neuen PR oder hier noch behoben werden ist euch überlassen.


1. Im docker-compose.yaml wird für service 'api' der container port '8000' gebunden. Im Dockerfile von der api wird uvicorn aber auf port 5000 gebunden.
2. Die DB migrations 'api/app/db/migrations/versions' erzeugen keine DB kompatibel zu den Datenmodellen (aufgefallen ist es mir vorallem bei 'Nodes' und 'Nodelist')
3. 'interventions_api' und 'parameter_definitions_api' geben teilweise noch invalide Responses zurück

2023-09-05 14:58 UTC, lucaspataro commented on api/src/api/app/apis/simulations_api.py
> +    "/scenarios/",
```suggestion
    "/scenarios",
```
Bitte keine "trailing slashes".

2023-09-05 14:58 UTC, lucaspataro commented on api/src/api/app/apis/simulations_api.py
> +    "/scenarios/{scenario_id}/",
```suggestion
    "/scenarios/{scenario_id}",
```

2023-09-05 14:58 UTC, lucaspataro commented on api/src/api/app/apis/simulations_api.py
> +    "/scenarios/{scenario_id}/simulations/{run_id}/migrations/",
```suggestion
    "/scenarios/{scenario_id}/simulations/{run_id}/migrations",
```

2023-09-06 07:50 UTC, slymon commented
Trailing Slashes sind entfernt, ich habe sie jetzt auch mal aus der Spec entfernt um hier konsistent zu bleiben

2023-09-06 07:55 UTC, slymon commented
Die Ports in der Dockerfile sind nun auch auf 8000 gestellt, die unterschiedlichen Ports haben aber sowieso keinen Einfluss auf das docker-compose. Das EXPOSE Kommando ist "nur" Dokumentation und das CMD wird übers compose nicht ausgeführt.

2023-09-06 08:53 UTC, NXXR commented
Bin auch schon an einem Review.
Bekomme allerdings ein paar Probleme beim aufsetzen (in der readme kommentiert).
Ich werd mal meinen vorläufigen review posten damit ich hoffentlich am Freitag das setup nochmal versuchen kann.

Hab das docker setup auf WSL2 und auf der Linux Maschine versucht aber alembic meckert bei der migration und danach bekomme ich "connection reset by peer" wenn ich versuche auf die api zu kommen.

2023-09-06 08:55 UTC, NXXR requested changes

2023-09-06 09:16 UTC, lucaspataro commented
> Zu Punkt 2 schonmal: Die Version ist eine alte Migrationsversion, diese sollte ehrlich gesagt gar nicht committed werden, mein Fehler! Um die richtige DB Version zu kriegen eine neue Migration generieren und pushen. Die Migrationen sollten immer nur auf dem System liegen auf dem sie deployed werden, dementsprechend nicht in git landen. Zum ausführen der neuen Migration bitte einfach in die README schauen :)

Das hatte ich ausgeführt, aber vllt ist da ja dann etwas schief gegangen weil er die bereits generierten Migrationen gefunden hatte.  Ich werde die mal löschen und es dann nochmal probieren.

2023-09-06 09:18 UTC, slymon commented
Ich teste gerade alles nochmal durch in diesem Repo. Ich muss gestehen, dass ich die Changes nur in unserem Repo getestet habe, nicht mehr in diesem. Ich melde mich in den nächsten 1-2h nochmal hier!

2023-09-06 09:26 UTC, lucaspataro commented
Wenn ich die vorhandenen Migrationen lösche, dann funktionieren die beiden Migrations-Befehle auch ohne Probleme 👍

2023-09-06 09:38 UTC, slymon commented
@NXXR ich hab beim ausführen der alembic statements keine Probleme. Luca scheinbar auch nicht. Benutzt ihr das gleiche Setup. 
Das compose läuft bei dir aber durch? 
Ich kann WSL2 nicht testen, da ich auf Mac unterwegs bin.

2023-09-06 10:14 UTC, slymon commented on api/readme.md
I intentionally put it there, because the README is just for the api module. We can merge it as the API section into the root README

2023-09-06 10:15 UTC, slymon commented on api/readme.md
> +Goto http://localhost:8000
Can you post the curl command?

2023-09-06 10:15 UTC, NXXR commented
@slymon  ich versuch am Freitag nochmal das komplette setup auf einer neuen WSL und auf der Linux Maschine.
Das compose lief porblemlos soweit ich mich erinnere; zumindest liefen alle container.

2023-09-06 10:18 UTC, NXXR commented on api/readme.md
> +Goto http://localhost:8000
pretty sure it was plain `curl localhost:8000` and once with hppt in front iirc.

2023-09-20 14:06 UTC, NXXR commented
@slymon @lucaspataro 
Ich hab jetzt mal versucht meinen Installationsprozess so gut es geht zu Dokumentieren.
Alles wurde auf einer Linux Maschine (Ubuntu 20.04.6 LTS x86_64) im DLR gemacht.

Gist:
https://gist.github.com/NXXR/b78fd1e8115b5799c66029260e7e1f2c

Hilfe 😅

2023-09-21 07:44 UTC, lucaspataro commented
@NXXR, @slymon und ich hatten oben festgestellt das die vorhandenen Migragtionsskripte fälschlicher weiße im Repo gelandet sind. Probier bitte nochmal in folgender Reihenfolge.

1. Lösche alle container / images und volumes
2. checkout repo / feature branch auf /localdatax (auf unseren Workstations hat docker zu wenig Berechtigungen in den Home-Verzeichnissen)
3. Lösche alle Dateien unter api/src/api/app/db/migrations/versions
4. Starte mit docker compose

2023-09-21 09:31 UTC, NXXR commented
> @NXXR, @slymon und ich hatten oben festgestellt das die vorhandenen Migragtionsskripte fälschlicher weiße im Repo gelandet sind. Probier bitte nochmal in folgender Reihenfolge.
> 
>     1. Lösche alle container / images und volumes
> 
>     2. checkout repo / feature branch auf /localdatax (auf unseren Workstations hat docker zu wenig Berechtigungen in den Home-Verzeichnissen)
> 
>     3. Lösche alle Dateien unter api/src/api/app/db/migrations/versions
> 
>     4. Mache wie in deinen Attemts ab docker compose up weiter

👍 das läuft jetzt scheinbar
localhost:8000 gibt
```
{
  detail: "Not Found"
}
```
zurück aber das sollte ja so sein wenn ich keinen API endpoint abfrage?
`localhost:8000/docs` zeigt jedenfalls die Swagger Seite für die API Specs als scheint das zu laufen :D

2023-09-21 09:36 UTC, slymon commented
> > @NXXR, @slymon und ich hatten oben festgestellt das die vorhandenen Migragtionsskripte fälschlicher weiße im Repo gelandet sind. Probier bitte nochmal in folgender Reihenfolge.
> > ```
> > 1. Lösche alle container / images und volumes
> > 
> > 2. checkout repo / feature branch auf /localdatax (auf unseren Workstations hat docker zu wenig Berechtigungen in den Home-Verzeichnissen)
> > 
> > 3. Lösche alle Dateien unter api/src/api/app/db/migrations/versions
> > 
> > 4. Mache wie in deinen Attemts ab docker compose up weiter
> > ```
> 
> 👍 das läuft jetzt scheinbar localhost:8000 gibt
> 
> ```
> {
>   detail: "Not Found"
> }
> ```
> 
> zurück aber das sollte ja so sein wenn ich keinen API endpoint abfrage? `localhost:8000/docs` zeigt jedenfalls die Swagger Seite für die API Specs als scheint das zu laufen :D

ganz genau!

2023-09-21 11:46 UTC, NXXR commented
Okay,

@slymon kannst du dann die migrations aus dem repo entfernen?
Oder in der `readme.md` erwähnen, dass man ggf die dateien löschen muss?

Wie sieht es mit dem Einpflegen von Daten in die API aus?
Wenn ich das richtig sehe wird über den `/scenarios/{scenario_id}/simulations` Endpoint einfach die binärdatei von der simulation hochgeladen und wird dann vom worker in die datenbank eingepflegt..
Funktioniert das schon? Haben @lucaspataro und du da schon Absprachen getroffen wie das funktioniert?

Um auf die neue API zu migrieren brauchen wir die Möglichkeit mindestens eine Test-Simulation in die Datenbank zu laden, im Idealfall die Summer Simulationen die aktuell auch in ESID sind.
Kannst du da ggf. noch eine Anleitung schreiben wie das läuft?

2023-09-22 06:31 UTC, slymon commented
> Okay,
> 
> @slymon kannst du dann die migrations aus dem repo entfernen? Oder in der `readme.md` erwähnen, dass man ggf die dateien löschen muss?
> 
> Wie sieht es mit dem Einpflegen von Daten in die API aus? Wenn ich das richtig sehe wird über den `/scenarios/{scenario_id}/simulations` Endpoint einfach die binärdatei von der simulation hochgeladen und wird dann vom worker in die datenbank eingepflegt.. Funktioniert das schon? Haben @lucaspataro und du da schon Absprachen getroffen wie das funktioniert?
> 
> Um auf die neue API zu migrieren brauchen wir die Möglichkeit mindestens eine Test-Simulation in die Datenbank zu laden, im Idealfall die Summer Simulationen die aktuell auch in ESID sind. Kannst du da ggf. noch eine Anleitung schreiben wie das läuft?

Ja, entferne die Migrations gleich. 

Das Laden von Daten in die API sollte funktionieren. Wir hatten den Endpunkt schon im letzten PR bereitgestellt, nachdem Luca und ich zusammen mit Jonas mal gesprochen hatten. Ich hab diesen Endpunkt jetzt ehrlich gesagt nicht nochmal getestet, weil ich gerade keine Daten dazu zur Verfügung hatte. 

Wir können aber gerne am Montag oder Deinstag dazu kurz sprechen.

2024-11-15 09:25 UTC, merged