OAuth2 (Keycloak) Integration with a Toy Endpoint
SciCompMod/ESID-Backend pull request #5
Opened 2024-11-26 07:53 UTC by Kanakanajm

I didn't dare to touch any files so I defined classes methods in files that are already there. Most of my codes are under `api/src/api/security_api.py` which contains several request filter methods that extract and verify token from the request header and then cast it into a simple [`User`](https://github.com/SciCompMod/ESID-Backend/blob/cec29e6bc9a581b1439433ae4001a8842d32a6bf/api/src/api/services/auth.py#L4) object defined in `api/src/api/services/auth.py`. The toy endpoint is defined in `api/src/api/app/apis/simulations_api.py` as [`create_protected_scenario`](https://github.com/SciCompMod/ESID-Backend/blob/cec29e6bc9a581b1439433ae4001a8842d32a6bf/api/src/api/app/apis/simulations_api.py#L51).

To test it out, you need to switch to [my branch](https://github.com/DLR-SC/ESID/tree/feature/auth-backend-integration) for the ESID frontend. There I attached realm information (required in the backend for verifying the token) in the request header to the toy endpoint.

Cheers

2024-11-29 09:54 UTC, JonasGilg requested changes
Looks good and seems to be working. Can you update the `openapi3_0.yaml` to reflect the new toy endpoint?

2024-11-29 11:15 UTC, Kanakanajm commented on api/src/api/app/db/models.py
I changed it and add a `owner` field before but then it seems I don't have to do that so I removed it.

2024-11-29 19:30 UTC, Kanakanajm commented on api/src/api/app/db/models.py
> Looks good and seems to be working. Can you update the `openapi3_0.yaml` to reflect the new toy endpoint?

Shouldn't the schema be generated automatically by FastAPI after defining the endpoints? When I add my toy endpoint, it is visible under `/docs`. Besides, i don't think openapi-generator can generate any [dependencies](https://fastapi.tiangolo.com/tutorial/dependencies/#what-is-dependency-injection) which the endpoint needs to filter out unauthorized users.

2024-11-29 19:30 UTC, Kanakanajm commented
> Looks good and seems to be working. Can you update the `openapi3_0.yaml` to reflect the new toy endpoint?

Shouldn't the schema be generated automatically by FastAPI after defining the endpoints? When I add my toy endpoint, it is visible under `/docs`. Besides, i don't think openapi-generator can generate any [dependencies](https://fastapi.tiangolo.com/tutorial/dependencies/#what-is-dependency-injection) which the endpoint needs to filter out unauthorized users.

2024-12-02 08:33 UTC, JonasGilg commented
> > Looks good and seems to be working. Can you update the `openapi3_0.yaml` to reflect the new toy endpoint?
> 
> Shouldn't the schema be generated automatically by FastAPI after defining the endpoints? When I add my toy endpoint, it is visible under `/docs`. Besides, i don't think openapi-generator can generate any [dependencies](https://fastapi.tiangolo.com/tutorial/dependencies/#what-is-dependency-injection) which the endpoint needs to filter out unauthorized users.

We actually generate the endpoints from the specification. Fast-API at the end shows the implemented endpoints on the /docs endpoint. In the end it should be identical to the specification.

2024-12-02 15:01 UTC, JonasGilg approved these changes

2024-12-06 09:09 UTC, merged